version: "3.9"
services:
  db:
    image: mysql
    container_name: spring-flyway-db
    environment:
      - MYSQL_ROOT_PASSWORD=12345
    ports:
      - "3306:3306"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 256M
