spring:
  datasource:
    url: jdbc:mysql://localhost:3306/football?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: 12345

    hikari:
      maximum-pool-size: 12
      minimum-idle: 4
      max-lifetime: 30000

  flyway:
    connect-retries: 2
    connect-retries-interval: 30s
    locations: [classpath:db/migration, classpath:db/callback]

  jpa:
    database: mysql
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: none

#   properties:
#     javax.persistence.schema-generation.scripts:
#       action: create
#        create-target: src/main/resources/schema-generation.sql

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
